language: minimal

env:
  - GCC_VERSION=7
  - GCC_VERSION=8

script:
  - docker build --build-arg GCC_VERSION=$GCC_VERSION --tag gcc-$GCC_VERSION .

after_success:
  - docker tag gcc-$GCC_VERSION floydci/debian-sid-gcc:$GCC_VERSION
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - docker push floydci/debian-sid-gcc:$GCC_VERSION
